// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zero.Infrastructure.DataBase;

namespace Zero.Infrastructure.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191219051354_initialize")]
    partial class initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zero.Core.Entities.Sys_Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Alias")
                        .HasColumnName("Alias")
                        .HasMaxLength(255);

                    b.Property<string>("BeforeCloseFun")
                        .HasColumnName("BeforeCloseFun")
                        .HasMaxLength(255);

                    b.Property<string>("Component")
                        .HasColumnName("Component")
                        .HasMaxLength(255);

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnName("CreatedByUserId");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnName("CreatedByUserName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasMaxLength(255);

                    b.Property<int?>("HideInMenu")
                        .HasColumnName("HideInMenu");

                    b.Property<string>("Icon")
                        .HasColumnName("Icon")
                        .HasMaxLength(128);

                    b.Property<int?>("IsDefaultRouter")
                        .HasColumnName("IsDefaultRouter");

                    b.Property<int?>("IsDeleted")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("Level")
                        .HasColumnName("Level");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnName("ModifiedByUserId");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnName("ModifiedByUserName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnName("ModifiedTime");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("NotCache")
                        .HasColumnName("NotCache");

                    b.Property<Guid?>("ParentId")
                        .HasColumnName("ParentId");

                    b.Property<string>("ParentName")
                        .HasColumnName("ParentName")
                        .HasMaxLength(50);

                    b.Property<int?>("Sort")
                        .HasColumnName("Sort");

                    b.Property<int?>("Status")
                        .HasColumnName("Status");

                    b.Property<string>("Url")
                        .HasColumnName("Url")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Sys_Menu");
                });

            modelBuilder.Entity("Zero.Core.Entities.Sys_Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("ActionCode")
                        .HasColumnName("ActionCode")
                        .HasMaxLength(80);

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnName("CreatedByUserId");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnName("CreatedByUserName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("Description")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasColumnName("Icon");

                    b.Property<int?>("IsDelete")
                        .HasColumnName("IsDelete");

                    b.Property<Guid?>("MenuId")
                        .HasColumnName("MenuId");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnName("ModifiedByUserId");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnName("ModifiedByUserName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnName("ModifiedTime");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("Status")
                        .HasColumnName("Status");

                    b.Property<int?>("Type")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Sys_Permission");
                });

            modelBuilder.Entity("Zero.Core.Entities.Sys_Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnName("CreatedByUserId");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnName("CreatedByUserName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasMaxLength(500);

                    b.Property<bool?>("IsBuiltin")
                        .HasColumnName("IsBuiltin");

                    b.Property<int?>("IsDeleted")
                        .HasColumnName("IsDeleted");

                    b.Property<bool?>("IsSuperAdministrator")
                        .HasColumnName("IsSuperAdministrator");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnName("ModifiedByUserId");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnName("ModifiedByUserName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnName("ModifiedTime");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("Status")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Sys_Role");
                });

            modelBuilder.Entity("Zero.Core.Entities.Sys_RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnName("PermissionId");

                    b.Property<Guid?>("RoleId")
                        .HasColumnName("RoleId");

                    b.HasKey("Id");

                    b.ToTable("Sys_RolePermission");
                });

            modelBuilder.Entity("Zero.Core.Entities.Sys_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Avatar")
                        .HasColumnName("Avatar")
                        .HasMaxLength(255);

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnName("CreatedByUserId");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnName("CreatedByUserName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasMaxLength(255);

                    b.Property<string>("DisplayName")
                        .HasColumnName("DisplayName")
                        .HasMaxLength(50);

                    b.Property<int?>("IsDeleted")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("IsLocked")
                        .HasColumnName("IsLocked");

                    b.Property<string>("LoginName")
                        .HasColumnName("LoginName")
                        .HasMaxLength(50);

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnName("ModifiedByUserId");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnName("ModifiedByUserName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnName("ModifiedTime");

                    b.Property<string>("Password")
                        .HasColumnName("Password")
                        .HasMaxLength(128);

                    b.Property<int?>("Status")
                        .HasColumnName("Status");

                    b.Property<int?>("UserType")
                        .HasColumnName("UserType");

                    b.HasKey("Id");

                    b.ToTable("Sys_User");
                });

            modelBuilder.Entity("Zero.Core.Entities.Sys_UserActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .HasColumnName("Action")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnName("ActionTime");

                    b.Property<int?>("ActionType")
                        .HasColumnName("ActionType");

                    b.Property<Guid?>("ActionUserId")
                        .HasColumnName("ActionUserId");

                    b.Property<Guid?>("ActionUserName")
                        .HasColumnName("ActionUserName");

                    b.Property<string>("ApiUrl")
                        .HasColumnName("ApiUrl")
                        .HasMaxLength(128);

                    b.Property<string>("Controller")
                        .HasColumnName("Controller")
                        .HasMaxLength(128);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasMaxLength(500);

                    b.Property<string>("IP")
                        .HasColumnName("IP")
                        .HasMaxLength(50);

                    b.Property<int?>("IsDeleted")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModelId")
                        .HasColumnName("ModelId");

                    b.HasKey("Id");

                    b.ToTable("Sys_UserActionLog");
                });

            modelBuilder.Entity("Zero.Core.Entities.Sys_UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<Guid?>("RoleId")
                        .HasColumnName("RoleId");

                    b.Property<Guid?>("UserId")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("Sys_UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
